/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiyafetstok;

import kiyafetstok.kadinKiyafet;
import kiyafetstok.erkekKiyafet;
import kiyafetstok.cocukKiyafet;
import java.awt.Button;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author ali_k
 */
public class kiyafetEkrani extends javax.swing.JFrame {

    kadinKiyafet btn = new kadinKiyafet();
    
    /**
     * Creates new form kiyafetEkranı
     */
    public kiyafetEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        erkekkiyafet = new javax.swing.JButton();
        cocukkiyafet = new javax.swing.JButton();
        kadinkiyafet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        erkekkiyafet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        erkekkiyafet.setText("Erkek Kıyafet");
        erkekkiyafet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erkekkiyafetActionPerformed(evt);
            }
        });

        cocukkiyafet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cocukkiyafet.setText("Çocuk Kıyafet");
        cocukkiyafet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocukkiyafetActionPerformed(evt);
            }
        });

        kadinkiyafet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kadinkiyafet.setText("Kadın Kıyafet");
        kadinkiyafet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kadinkiyafetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(kadinkiyafet, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(erkekkiyafet, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cocukkiyafet, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(erkekkiyafet, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kadinkiyafet, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cocukkiyafet, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kadinkiyafetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kadinkiyafetActionPerformed
        dispose();
        kadinKiyafet yeni = new kadinKiyafet();
        yeni.setVisible(true);
        yeni.parent = this;


    }//GEN-LAST:event_kadinkiyafetActionPerformed

    private void erkekkiyafetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erkekkiyafetActionPerformed
          dispose();
        erkekKiyafet yeni = new erkekKiyafet();
        yeni.setVisible(true);
        yeni.parent = this;
    }//GEN-LAST:event_erkekkiyafetActionPerformed

    private void cocukkiyafetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocukkiyafetActionPerformed
          dispose();
        cocukKiyafet yeni = new cocukKiyafet();
        yeni.setVisible(true);
        yeni.parent = this;
    }//GEN-LAST:event_cocukkiyafetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kiyafetEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kiyafetEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kiyafetEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kiyafetEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new kiyafetEkrani().setVisible(true);
        });

    }

    public kullanicijframe parent;
    public erkekKiyafet child;
    public kadinKiyafet child3;
    public cocukKiyafet child6;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cocukkiyafet;
    private javax.swing.JButton erkekkiyafet;
    private javax.swing.JButton kadinkiyafet;
    // End of variables declaration//GEN-END:variables
}
